# Generated by Django 4.1 on 2022-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_alter_place2_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place2',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
